### ISSUE TITLE
How can I embed videos in sphinx site?

### ISSUE THREAD

**Issue by josesanchez1815** [josesanchez1815/sphinx-vidlet-hosting#3]
I need help figuring out how to include videos like the following on a sphinx site. 

![image](https://user-images.githubusercontent.com/62918474/84090978-0a433d00-a9a8-11ea-9e12-35eb07ecba8a.png)

**Comment by josesanchez1815** [comment]
Any thoughts if you have time...@luizirber

**Comment by luizirber** [comment]
The nice thing about seeing this in a readthedocs site is that they include a link to check the source on github:
![image](https://user-images.githubusercontent.com/6642/84096773-456a5e00-a9f2-11ea-8acc-273a4f5aab10.png)
If you click on "Edit on GitHub" you'll be sent to https://github.com/readthedocs/readthedocs.org/blob/4eadf26b562920e4433dc53e5fe0c8e6fc7dd913/docs/intro/getting-started-with-sphinx.rst
and you can click on the "Raw" button:
![image](https://user-images.githubusercontent.com/6642/84096843-7480cf80-a9f2-11ea-9deb-2c204f8ce21a.png)
to see the source for that .rst file:
https://raw.githubusercontent.com/readthedocs/readthedocs.org/4eadf26b562920e4433dc53e5fe0c8e6fc7dd913/docs/intro/getting-started-with-sphinx.rst

In this case, that youtube video is included as
```rst
Quick start video
-----------------

This screencast will help you get started or you can
:ref:`read our guide below <intro/getting-started-with-sphinx:Quick start>`.

.. raw:: html

    <div style="text-align: center; margin-bottom: 2em;">
    <iframe width="100%" height="350" src="https://www.youtube.com/embed/oJsUvBQyHBs?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
    </div>
```
which is the default recommended way that youtube recommends for embedding videos (you can see it by clicking in the "Share" button for any youtube video).

Hopefully this is useful =]

**Comment by luizirber** [comment]
You can also embed AggieVideo content, according to https://ucdavisit.service-now.com/servicehub/?id=ucd_kb_article&sysparm_article=KB0003248

**Comment by josesanchez1815** [comment]
Thanks Luiz!
![image](https://user-images.githubusercontent.com/62918474/84173852-b0d42000-aa32-11ea-9785-9a1b9aeb7ae0.png)
